# Generated by Django 4.2.6 on 2023-10-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Indicate the type of tides')),
            ],
        ),
        migrations.CreateModel(
            name='age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Unit of warm mesaurement')),
            ],
        ),
        migrations.CreateModel(
            name='carbonCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Indicates the presence or absence about.')),
            ],
        ),
        migrations.CreateModel(
            name='magneticFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Indicates the presence or absence about.')),
            ],
        ),
        migrations.CreateModel(
            name='measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Indicate the type of tides')),
            ],
        ),
        migrations.CreateModel(
            name='orbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Unit of warm mesaurement')),
            ],
        ),
        migrations.CreateModel(
            name='planetSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='plateTectonic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Age of the planet')),
            ],
        ),
        migrations.CreateModel(
            name='plateTectonics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Indicates the presence or absence about.')),
            ],
        ),
        migrations.CreateModel(
            name='starSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='tides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Indicate the type of tides')),
            ],
        ),
        migrations.CreateModel(
            name='unitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Unit of warm mesaurement')),
            ],
        ),
        migrations.CreateModel(
            name='planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_planet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='media/static/img/')),
                ('composition', models.CharField(max_length=100)),
                ('warm', models.CharField(max_length=100)),
                ('ice_sheet_extend', models.CharField(max_length=100)),
                ('oceans', models.CharField(max_length=100)),
                ('ocean_extend', models.CharField(max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activity')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.age')),
                ('carbonCycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carboncycle')),
                ('magneticFields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.magneticfields')),
                ('orbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orbit')),
                ('planetSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planetsize')),
                ('plateTectonics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platetectonics')),
                ('starSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.starsize')),
                ('tides', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tides')),
                ('unitMeasurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unitmeasurement')),
                ('volcanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.measure')),
            ],
        ),
    ]
