# Generated by Django 4.2.6 on 2023-10-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='age',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carboncycle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='magneticfields',
            name='description',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orbit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='planetsize',
            name='description',
        ),
        migrations.RemoveField(
            model_name='platetectonic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='platetectonics',
            name='description',
        ),
        migrations.RemoveField(
            model_name='starsize',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tides',
            name='description',
        ),
        migrations.RemoveField(
            model_name='unitmeasurement',
            name='description',
        ),
    ]
